Sleitnick/Knit

src/Knit/Util/Signal.lua
This is faster because it avoids indexing the same thing twice for operations.
=> Faster operations.

src/Knit/Util/Remote/RemoteProperty.lua
While messing around with the framework, I noticed that it said that a bool was not a supported value type, so I investigated and found that the wrong type was used in the type class map.
Though it may be necessary to include "bool" as well. All I did was change it to "boolean"
=> typeof(true|false) == "boolean" not "bool"

src/Knit/KnitClient.lua, src/Knit/KnitServer.lua, src/Knit/Util/Remote/RemoteProperty.lua
The justification behind this change is to replicate tables using RemoteFunctions and RemoteEvents instead of StringValue. StringValues force JSON serialization, which only allows primitive data, and thus instances cannot be contained within the table data. This is _not_ the case for RFs and REs, meaning users can include instances within table data and it will replicate just fine (assuming the instance is available to the clients).
=> Better table replication for RemoteProperty objects

docs/util.md, src/Knit/Util/Symbol.lua, src/Knit/Util/Thread.lua
`Thread.DelayRepeat` always waits the initial time interval before the first execution of its given function. In some use-cases, it would be helpful for the function to be executed right away (in the same way that `Thread.Spawn` would execute it right away; after a single heartbeat).
This change introduces a _non_-backwards-compatible change to the function signature, where an `immediate` boolean parameter is added: `Thread.DelayRepat(intervalTime, func, immediate, ...)`. This would break existing code that relies on the varargs `...` to pass parameters to the function. The fix would be to add `false` where the `immediate` parameter would now be.
=> Add ability to execute function immediately in DelayRepeat

docs/services.md, docs/util.md, src/Knit/KnitClient.lua, src/Knit/Util/Remote/RemoteSignal.lua, test/tests/Specs/Knit.spec.lua
Rename RemoteEvent to RemoteSignal for the sake of naming consistencies. This has obvious backwards-compatibility issues. The fix is to simply rename any references of RemoteEvent to RemoteSignal. There are no behavior changes.
=> Rename RemoteEvent to RemoteSignal

src/Knit/Util/Remote/ClientRemoteProperty.lua
The line `self._set:Destroy()` was throwing errors because `_set` doesn't exist. Line has been removed. `_set` had existed in a previous version and its removal was overlooked previously.
=> Remove ref to nil field

mkdocs.yml
Knit's documentation is a health hazard. I believe I'm suffering from eye fatigue looking at the bright white colors.
This will acknowledge any health concerns as well as provide a seamless reading experience.
=> Dark theme support based on preference

src/Knit/Util/Signal.lua
Fixes a data leak caused by firing signals that had no connections, which was causing the arguments to be cached forever.
=> Fix Signal Leak

src/Knit/Util/Component.lua
Components should no longer user StringValues for storing the server ID, and instead should use attributes.
=> Use attributes for component server ID

docs/util.md, src/Knit/Util/Signal.lua
Add constructor to create simple proxy signal to a built-in RBXScriptSignal.
=> Signal proxy

src/Knit/Util/Loader.lua, src/Knit/Util/TableUtil.lua
**Util.TableUtil**
- Edited array traversal to use ipairs instead of index for loop
- Boatbomber's benchmark revealed new traversal to be ~14% faster than current method
**Util.Loader**
- Edited array insertion to use index variable instead as table.insert function call is expensive
- Boatbomber's benchmark revealed insertion with index to be ~4x faster than table.insert
=> Optimize array traversal and insertion

docs/knitapi.md, src/Knit/KnitServer.lua, src/Knit/Util/Loader.lua, src/Knit/Util/TableUtil.lua
As the root of many bugs, being able to use Knit.GetService in another service is a commonly requested feature. Alternatively, we can add a warning in place of the return.
=> Add Knit.GetService for services

docs/vscodesnippets.md
Knit Controller documentation was the same as the Knit Service documentation, due to copy and pasting the same text
=> Fix copy and paste typo

src/Util/Component.lua
The logic done in this loop is already done in a later stage. It does not need to happen twice.
=> Remove redundant loop in Component module

src/Util/Timer.lua
The signal import requires Knit then uses `Knit.Util.Signal` to import the module,
this causes a runtime error in Roblox-TS as Knit isn't a parent of ReplicatedStorage,
instead its a descendant.
I've tested it and I get no initial errors on the require. This comes down to personal preference though.
=> Fix Imports for Timer module

src/KnitClient.lua, src/KnitServer.lua
Knit does not always have the Util folder or the Version object loaded when it tries to reference it, leading to some issues caused by the race condition:
This pull request adds :WaitForChild statements to ensure that Knit doesn't fail to start at no fault to the developer using it.
=> Fix race conditions for Knit

src/Util/Component.lua
I introduced a bug (see #139) when trying to remove a redundant loop. The bug introduced would allow for errors to occur whenever the component was observed immediately. This was not caught before due to the use of the Thread library, which has been replaced by the roblox task library. I considered using the `task.defer` method which would work, but using two loops is probably a more future-proof way to fix the issue.
=> Fix issues in Component with more than 1 RequiredComponent

src/KnitServer.lua
Allows middleware to be used in Knit. Fixes #176 and makes it easier to log anything happening within a Knit project.
=> Add KnitOptions to server for Comm middleware

docs/controllers.md
Example contains use case where the expression 'Knit.Controllers.CameraController' is used, which does not work in current Knit versions. Replaced documentation with 'Knit.GetController("CameraController")'.
=> Replace '.Controllers' with '.GetController'

docs/services.md
One part of the docs was still doing Knit.Services.PointService which is not doable in Knit anymore.
=> Docs: Removed Knit.Services.Service in favour of Knit.GetService()

docs/services.md
In the description of Section "Events (Server-to-Client)", there is an inconsistent syntax; In the description it is `Knit:CreateSignal()`, whereas in the example code, it is `Knit.CreateSignal()`.
=> Fixed inconsistent syntax than example in docs/services.md

.github/workflows/ci.yaml, .github/workflows/release.yaml, CHANGELOG.md, docs/gettingstarted.md, src/KnitClient.lua, src/KnitServer.lua, src/wally.toml
- Adds `GetServices()` and `GetControllers()` methods.
- Freeze `services` and `controllers` tables.
Note: This does _not_ include the client-side `services` table. In other words, `GetServices()` is a server-only method & not available on the client. Items in this table are lazy-initialized as accessed, and require lookup into the data model. Thus, there is no adequate way to get all of them with the current setup.
=> GetServices and GetControllers
